name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
